# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x17120fff
bordercolor = 0x9e8e81ff
focuscolor = 0xffb873ff
maximizescreencolor = 0xe2c0a4ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xc1cc99ff
globalcolor = 0x6a3b00ff
overlaycolor = 0x59422dff
